# Generated by Django 4.2.11 on 2024-08-26 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0002_rename_articles_article"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={"ordering": ("-updated", "-published")},
        ),
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("TC", "TECNOLOGY"),
                    ("SP", "SPORT"),
                    ("HT", "HEALTH"),
                    ("HB", "HOBBIES"),
                ],
                default="TC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads"),
        ),
    ]
