# Generated by Django 4.2.11 on 2024-08-26 14:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("articles", "0003_alter_article_options_article_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[("DRAFT", "Draft"), ("PUBLISHED", "Published")],
                default="DRAFT",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.CharField(
                choices=[
                    ("TC", "Technology"),
                    ("SP", "Sport"),
                    ("HT", "Health"),
                    ("HB", "Hobbies"),
                    ("DS", "Design"),
                    ("SC", "Science"),
                ],
                default="TC",
                max_length=2,
            ),
        ),
    ]
